name: Docker Hub Description
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - .github/workflows/dockerhub-description.yml
jobs:
  docker-hub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.1.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: berkus/kroki-server
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./DOCKERHUB.md
